/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;

import org.apache.logging.log4j.LogManager;

import controller.DashBoard;
import controller.PanelController;
import object.User;
import object.Vehicle;

/**
 *
 * @author Xingan_Wan
 */
public class EditVehicleGUI extends javax.swing.JPanel {
    
    /**
     * Creates new form DriverInfo
     */
    public EditVehicleGUI(DashBoard cp, User user) {
        this.cp = cp;
        this.pc = cp.getPanelController();
        this.vehicle = (user.getVehicle() == null) ? new Vehicle("Model", 0) : user.getVehicle();
        this.user = user;
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vInfoLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        capaLabel = new javax.swing.JLabel();
        spaceLabel = new javax.swing.JLabel();
        modelFormattedTextField = new javax.swing.JFormattedTextField(vehicle.getModel());
        capaFormattedTextField = new javax.swing.JFormattedTextField(vehicle.getPassengerCap());
        spaceFormattedTextField = new javax.swing.JFormattedTextField(vehicle.getStorageSpace());
        okButton = new javax.swing.JButton();
        bottomSeparator = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        topSeparator = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(700, 500));

        vInfoLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        vInfoLabel.setText("Vehicle Information");

        modelLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        modelLabel.setText("Model (Description)");

        capaLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        capaLabel.setText("Capacity (People)");

        spaceLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        spaceLabel.setText("storage Space (Cases)");

        okButton.setBackground(new java.awt.Color(0, 102, 0));
        okButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bottomSeparator)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topSeparator)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capaLabel)
                    .addComponent(spaceLabel)
                    .addComponent(modelLabel))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capaFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(modelFormattedTextField)
                    .addComponent(spaceFormattedTextField))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vInfoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(topSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(modelFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capaLabel)
                    .addComponent(capaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaceLabel)
                    .addComponent(spaceFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232)
                .addComponent(bottomSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backButton, okButton});

    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        pc.closeFrame();
    }//GEN-LAST:event_backButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        vehicle.setModel(modelFormattedTextField.getText());
        vehicle.setPassengerCap(Integer.parseInt(capaFormattedTextField.getText()));
        vehicle.setStorageSpace(spaceFormattedTextField.getText());
        
        user.setVehicle(vehicle);
        pc.closeFrame();
    }//GEN-LAST:event_okButtonActionPerformed
    
    public static void main(String[] args) {
        // take place on thread other than main thread
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Windows".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    LogManager.getLogger().error(e.getMessage(), e);
                }
                // turn off metal's use of bold fonts
                UIManager.put("swing.boldMetal", Boolean.FALSE);
                
                DashBoard cp = new DashBoard();
                cp.load();
                cp.getPanelController().changeFrame(new EditVehicleGUI(cp, null));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JSeparator bottomSeparator;
    private javax.swing.JFormattedTextField capaFormattedTextField;
    private javax.swing.JLabel capaLabel;
    private javax.swing.JFormattedTextField modelFormattedTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JFormattedTextField spaceFormattedTextField;
    private javax.swing.JLabel spaceLabel;
    private javax.swing.JSeparator topSeparator;
    private javax.swing.JLabel vInfoLabel;
    // End of variables declaration//GEN-END:variables
    
    @SuppressWarnings("unused")
    private DashBoard cp;
    private PanelController pc;
    private Vehicle vehicle;
    private User user;
    private static final long serialVersionUID = 7794269541984046099L;
}
