/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import controller.PanelController;
/**
 *
 * @author Xingan_wan
 */
public class HomePageGUI extends javax.swing.JPanel {

    /**
     * Creates new form HomePageGUI
     */
    public HomePageGUI(PanelController pm) {
        this.pm = pm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        topSeparator = new javax.swing.JSeparator();
        tripLabel = new javax.swing.JLabel();
        tripButton = new javax.swing.JButton();
        messageBoardLabel = new javax.swing.JLabel();
        messageBoardButton = new javax.swing.JButton();
        userInfoLabel = new javax.swing.JLabel();
        accountSettingButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));

        welcomeLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        welcomeLabel.setText("Welcome To Bear Rides!");

        tripLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        tripLabel.setText("Your Coming Trip:");

        tripButton.setBackground(new java.awt.Color(51, 153, 0));
        tripButton.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tripButton.setText("Your Trip");
        tripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripButtonActionPerformed(evt);
            }
        });

        messageBoardLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        messageBoardLabel.setText("Find A Trip:");

        messageBoardButton.setBackground(new java.awt.Color(255, 255, 0));
        messageBoardButton.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        messageBoardButton.setText("Message Board");
        messageBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageBoardButtonActionPerformed(evt);
            }
        });

        userInfoLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        userInfoLabel.setText("Become a driver/ Change your Info:");

        accountSettingButton.setBackground(new java.awt.Color(0, 102, 204));
        accountSettingButton.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        accountSettingButton.setText("Account Setting");
        accountSettingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 51, 51));
        backButton.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topSeparator)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tripLabel)
                                    .addComponent(messageBoardLabel)
                                    .addComponent(userInfoLabel))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accountSettingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(messageBoardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tripButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripLabel)
                    .addComponent(tripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageBoardLabel)
                    .addComponent(messageBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInfoLabel)
                    .addComponent(accountSettingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripButtonActionPerformed

    private void messageBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageBoardButtonActionPerformed
        pm.changeFrame(new MessageBoardGUI(pm));
    }//GEN-LAST:event_messageBoardButtonActionPerformed

    private void accountSettingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingButtonActionPerformed
        // TODO add your handling code here:
        pm.changeFrame(new UserGUI(pm));
    }//GEN-LAST:event_accountSettingButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        pm.closeFrame();
    }//GEN-LAST:event_backButtonActionPerformed

    public static void main(String[] args) throws Exception{
        // take place on thread other than main thread
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Windows".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {} catch (InstantiationException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (IllegalAccessException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (UnsupportedLookAndFeelException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                
                // turn off metal's use of bold fonts
                UIManager.put("swing.boldMetal", Boolean.FALSE);
                PanelController pm = new PanelController();
                pm.changeFrame(new HomePageGUI(pm));
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountSettingButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton messageBoardButton;
    private javax.swing.JLabel messageBoardLabel;
    private javax.swing.JSeparator topSeparator;
    private javax.swing.JButton tripButton;
    private javax.swing.JLabel tripLabel;
    private javax.swing.JLabel userInfoLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    PanelController pm;
}
