/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import org.apache.logging.log4j.LogManager;

import controller.DashBoard;
import controller.MessageCollectionController;
import controller.PanelController;
import object.Trip;
import object.User;

/**
 *
 * @author Xingan_Wan
 */
public class TripBoardGUI extends javax.swing.JPanel {

    /**
     * Creates new form MessageTableGUI1
     */
    public TripBoardGUI(DashBoard cp, User user) {
        //later make load from file
        this.cp = cp;
        tc = cp.getMessageCollectionController();
        tripTable = new JTable();
        pc = cp.getPanelController();
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        tripTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();

        tripTable.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        
        DefaultTableModel model = new DefaultTableModel() {
            private static final long serialVersionUID = -2303248161806139568L;
            boolean[] canEdit = new boolean [] {false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        
        for(Trip trip : user.getTrips()) {
            model.addRow(new Trip[]{trip});
        }
        tripTable.setModel(model);
        
        tripTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tripTable.setFillsViewportHeight(true);
        tripTable.setRowHeight(20);
        tripTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tripTable.getTableHeader().setReorderingAllowed(false);
        tripTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageTableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tripTable);
        if (tripTable.getColumnModel().getColumnCount() > 0) {
            tripTable.getColumnModel().getColumn(0).setPreferredWidth(500);
        }

        backButton.setBackground(new java.awt.Color(0, 102, 0));
        backButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        pc.closeFrame();
    }//GEN-LAST:event_backButtonActionPerformed

    private void messageTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageTableMouseClicked
        // TODO add your handling code here:
        if (2 == evt.getClickCount()) {
            int mouseIndex = tripTable.rowAtPoint(evt.getPoint());
            mouseIndex = tripTable.convertRowIndexToModel(mouseIndex);
            pc.changeFrame(new ViewTripGUI(cp, ((Trip) tripTable.getValueAt(mouseIndex, 0)).getMessage()));
        }
        
    }//GEN-LAST:event_messageTableMouseClicked

    public static void main(String[] args) throws Exception {
        // take place on thread other than main thread
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Windows".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    LogManager.getLogger().error(e.getMessage(), e);
                }
                // turn off metal's use of bold fonts
                UIManager.put("swing.boldMetal", Boolean.FALSE);
                
                DashBoard cp = new DashBoard();
                cp.load();
                cp.getPanelController().changeFrame(new TripBoardGUI(cp, null));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable tripTable;
    // End of variables declaration//GEN-END:variables
    
    private DashBoard cp;
    @SuppressWarnings("unused")
    private MessageCollectionController tc;
    private PanelController pc;
    private User user;
    private static final long serialVersionUID = 5164463894978645312L;
}
