/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.DashBoard;
import controller.MessageCollectionController;
import controller.PanelController;

/**
 *
 * @author WAN
 */
public class ViewTripGUI extends javax.swing.JPanel {
    
    /**
     * Creates new form TripGUI
     */
    public ViewTripGUI(DashBoard cp) {
        this.cp = cp;
        this.tc = cp.getMessageCollectionController();
        this.pc = cp.getPanelController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        driverLabel = new javax.swing.JLabel();
        viewTripLabel = new javax.swing.JLabel();
        separator3 = new javax.swing.JSeparator();
        driverTextField = new javax.swing.JTextField();
        ridersLabel = new javax.swing.JLabel();
        ridersTextField = new javax.swing.JTextField();
        originTimeLabel = new javax.swing.JLabel();
        originTimeTextField = new javax.swing.JTextField();
        originLocLabel = new javax.swing.JLabel();
        originLocTextField = new javax.swing.JTextField();
        desTimeLabel = new javax.swing.JLabel();
        desTimeTextField = new javax.swing.JTextField();
        desLocLabel = new javax.swing.JLabel();
        desLocTextField = new javax.swing.JTextField();
        returnTimeLabel = new javax.swing.JLabel();
        returnTimeTextField = new javax.swing.JTextField();
        returnLocLabel = new javax.swing.JLabel();
        returnLocTextField = new javax.swing.JTextField();
        passenCapLabel = new javax.swing.JLabel();
        passenCapTextField = new javax.swing.JTextField();
        messageButton = new javax.swing.JButton();
        separator1 = new javax.swing.JSeparator();
        separator2 = new javax.swing.JSeparator();

        backButton.setBackground(new java.awt.Color(0, 102, 0));
        backButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        driverLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        driverLabel.setText("Driver");

        viewTripLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        viewTripLabel.setText("View Trip");

        driverTextField.setEditable(false);

        ridersLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        ridersLabel.setText("Riders");

        ridersTextField.setEditable(false);

        originTimeLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        originTimeLabel.setText("Origin Time");

        originTimeTextField.setEditable(false);

        originLocLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        originLocLabel.setText("Origin Location");

        originLocTextField.setEditable(false);

        desTimeLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        desTimeLabel.setText("Destination Time");

        desTimeTextField.setEditable(false);

        desLocLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        desLocLabel.setText("Destination Location");

        desLocTextField.setEditable(false);

        returnTimeLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        returnTimeLabel.setText("Return Time");

        returnTimeTextField.setEditable(false);

        returnLocLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        returnLocLabel.setText("Return Location");

        returnLocTextField.setEditable(false);

        passenCapLabel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        passenCapLabel.setText("Passenger Capcity");

        passenCapTextField.setEditable(false);

        messageButton.setBackground(new java.awt.Color(0, 102, 0));
        messageButton.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        messageButton.setText("Message");
        messageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driverLabel)
                            .addComponent(viewTripLabel)
                            .addComponent(ridersLabel)
                            .addComponent(originTimeLabel)
                            .addComponent(originLocLabel)
                            .addComponent(passenCapLabel)
                            .addComponent(returnTimeLabel)
                            .addComponent(returnLocLabel)
                            .addComponent(desTimeLabel)
                            .addComponent(desLocLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driverTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ridersTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originTimeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originLocTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passenCapTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnTimeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnLocTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(messageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))
                            .addComponent(desTimeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desLocTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(separator2))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separator1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewTripLabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverLabel)
                    .addComponent(driverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ridersLabel)
                    .addComponent(ridersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originTimeLabel)
                    .addComponent(originTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originLocLabel)
                    .addComponent(originLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desTimeLabel)
                    .addComponent(desTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desLocLabel)
                    .addComponent(desLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnTimeLabel)
                    .addComponent(returnTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnLocLabel)
                    .addComponent(returnLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passenCapLabel)
                    .addComponent(passenCapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        pc.closeFrame();
    }//GEN-LAST:event_backButtonActionPerformed

    private void messageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel desLocLabel;
    private javax.swing.JTextField desLocTextField;
    private javax.swing.JLabel desTimeLabel;
    private javax.swing.JTextField desTimeTextField;
    private javax.swing.JLabel driverLabel;
    private javax.swing.JTextField driverTextField;
    private javax.swing.JButton messageButton;
    private javax.swing.JLabel originLocLabel;
    private javax.swing.JTextField originLocTextField;
    private javax.swing.JLabel originTimeLabel;
    private javax.swing.JTextField originTimeTextField;
    private javax.swing.JLabel passenCapLabel;
    private javax.swing.JTextField passenCapTextField;
    private javax.swing.JLabel returnLocLabel;
    private javax.swing.JTextField returnLocTextField;
    private javax.swing.JLabel returnTimeLabel;
    private javax.swing.JTextField returnTimeTextField;
    private javax.swing.JLabel ridersLabel;
    private javax.swing.JTextField ridersTextField;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JLabel viewTripLabel;
    // End of variables declaration//GEN-END:variables
    
    @SuppressWarnings("unused")
    private DashBoard cp;
    @SuppressWarnings("unused")
    private MessageCollectionController tc;
    private PanelController pc;
    private static final long serialVersionUID = 8028047312528638693L;
}
