package gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JPanel;

public class ViewProfileGUI extends JPanel {
    
    /**
     * Creates new form UserGUI
     */
    public ViewProfileGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        userInfoLabel = new javax.swing.JLabel();
        reqLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        registerAsDriverButton = new javax.swing.JButton();
        firstNameFormattedTextField = new javax.swing.JFormattedTextField();
        lastNameFormattedTextField = new javax.swing.JFormattedTextField();
        ageFormattedTextField = new javax.swing.JFormattedTextField();
        genderFormattedTextField = new javax.swing.JFormattedTextField();
        contactFormattedTextField = new javax.swing.JFormattedTextField();
        emailFormattedTextField = new javax.swing.JFormattedTextField();
        upperSeparator = new javax.swing.JSeparator();
        LowerSeparator = new javax.swing.JSeparator();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        editDriverInfoButton = new javax.swing.JButton();

        userInfoLabel.setText("Change personal Information");

        reqLabel.setText("* Indicates required field");

        firstnameLabel.setText("First Name*");

        lastnameLabel.setText("Last Name*");

        ageLabel.setText("Age*");

        genderLabel.setText("Gender");

        contactLabel.setText("Contact (Phone/weChat)*");

        emailLabel.setText("Email Address*");

        registerAsDriverButton.setText("Register as a Driver");

        firstNameFormattedTextField.setText("jFormattedTextField1");

        lastNameFormattedTextField.setText("jFormattedTextField1");

        ageFormattedTextField.setText("jFormattedTextField1");

        genderFormattedTextField.setText("jFormattedTextField1");

        contactFormattedTextField.setText("jFormattedTextField1");

        emailFormattedTextField.setText("jFormattedTextField1");

        saveButton.setText("Save");

        cancelButton.setText("Cancel");

        editDriverInfoButton.setText("Edit your Driver Info");

        this.window = new JPanel();
        this.window.setVisible(true);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.window);
        window.setLayout(layout);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LowerSeparator)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(userInfoLabel)
                                    .addGap(93, 93, 93)
                                    .addComponent(reqLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstnameLabel)
                                        .addComponent(lastnameLabel)
                                        .addComponent(ageLabel)
                                        .addComponent(genderLabel)
                                        .addComponent(contactLabel)
                                        .addComponent(emailLabel))
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ageFormattedTextField)
                                        .addComponent(lastNameFormattedTextField)
                                        .addComponent(firstNameFormattedTextField)
                                        .addComponent(genderFormattedTextField)
                                        .addComponent(contactFormattedTextField)
                                        .addComponent(emailFormattedTextField))))
                            .addComponent(upperSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editDriverInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerAsDriverButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInfoLabel)
                    .addComponent(reqLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upperSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstnameLabel)
                    .addComponent(firstNameFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(lastNameFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerAsDriverButton)
                    .addComponent(editDriverInfoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LowerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ageFormattedTextField, contactFormattedTextField, emailFormattedTextField, firstNameFormattedTextField, genderFormattedTextField, lastNameFormattedTextField});
        
    }// </editor-fold>//GEN-END:initComponents

    public void draw(JFrame frame) {     
    	frame.getContentPane().removeAll();
    	frame.add(this.window);
    	frame.revalidate();
    	frame.repaint();
    }
    
    public List<String> getUserInfo(){
    	List<String> userInfo = new ArrayList<String>();
    	
    	userInfo.add(this.firstNameFormattedTextField.toString());
    	userInfo.add(this.lastNameFormattedTextField.toString());
    	userInfo.add(this.ageFormattedTextField.toString());
    	userInfo.add(this.genderFormattedTextField.toString());
    	userInfo.add(this.contactFormattedTextField.toString());
    	userInfo.add(this.emailFormattedTextField.toString());
    	
    	return userInfo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel window;
    private javax.swing.JSeparator LowerSeparator;
    private javax.swing.JFormattedTextField ageFormattedTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JFormattedTextField contactFormattedTextField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JButton editDriverInfoButton;
    private javax.swing.JFormattedTextField emailFormattedTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JFormattedTextField firstNameFormattedTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JFormattedTextField genderFormattedTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JFormattedTextField lastNameFormattedTextField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JButton registerAsDriverButton;
    private javax.swing.JLabel reqLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JSeparator upperSeparator;
    private javax.swing.JLabel userInfoLabel;
    // End of variables declaration//GEN-END:variables
    
    private static final long serialVersionUID = -814443054477085577L;
}
